### PR TITLE
Probably fix bug with 5, 4 segments

### PR DESCRIPTION
**Pull request by oncecreated**
Hi!  

I use G213Colors (without gui) on Windows, but encountered a problem. I can chanage color only one times after reboot. I additionally reverse engineering G213 and I solved the the problem. I'm find one more command and named it "reset", also I noticed that offical softaware recive data and I too add this in code. Now all segments work fine on Windows, but I dont have an opportunity test it in Linux. Сould you check its work?

### CODE REVIEW

**Comment by dereisele** [comment]
Hi,

First of, thanks for using and contributing to our project.
Unfortunaly, your changes results on my machine in a resource busy error.

[Traceback](https://pastebin.com/u6izspAQl)

**Comment by dereisele** [comment]
After a little bit of fiddeling, I found out, that `device.set_configuration()` and `receiveData()` cause this resource busy error independently. In audition, when `sendData(resetCommand)` is executed, I'm only able to control the first segment.

I think you should contact @SebiTimeWaster since I have only a rough idea of how low-level USB works in python.

**Comment by SebiTimeWaster** [comment]
Interesting!
In my blog ( https://www.timewasters-place.com/how-to-use-the-logitech-g213-prodigy-gaming-keyboard-under-linux/ ) i described a command always being sent before any other color command that could be considered a "reset" command, but in my tests i found no different behavior when i send it vs. when i didn't send it, so i omitted it from my code.

Interestingly the command is 11ff0c0a00000000000000000000000000000000, whereas @oncecreated command is 11ff0c0c00000000000000000000000000000000, may i ask where you have this command from? did you do some further sniffing?

**Comment by oncecreated** [comment]
Yes, I use proprietary software USBlyzer (http://www.usblyzer.com/download.htm) .
Strangely, but now I'm getting new value for "reset" it `11ff0c0b00000000000000000000000000000000`.
Keyboard response is `11ff0c0b06000100000000000000000000000000`.
It looks like counter.

**Comment by oncecreated** [comment]
After some tests I made sure that "reset" not needed. But read answer from keyboard is needed. Please check work now.

**Comment by dereisele** [comment]
Now, it work's but only without the `device.set_configuration()`, so I ended up testing whether this program is run under Linux or Windows. So please check out the [next Branch](https://github.com/derEisele/G213Colors/tree/next).

**Comment by oncecreated** [comment]
Sorry, but `device.set_configuration()` do not even need on Windows. Adding it to code is my mistake.

**Comment by dereisele** [comment]
You're welcome!

**Comment by SebiTimeWaster** [comment]
you forgot to remove the "import platform" statement in both files...

anyway, i will try out this solution and backport it to my repo.

funny enough this reminds me of another project where i control a plotter via serial connection, and without reading *some* data back from the connection the plotter would not execute the last 2 commands. i never found out why that is, and honestly i expected the usb protocol to be better in that regard.

**Comment by dereisele** [comment]
I also found an unused `import sys`. :smile:

**Pull request merged**
